apiVersion: v1
kind: Pod          #(object's kind)
metadata:          #(when we launch something, we put      
  name: mypod1    # that data in metadata block)
  labels:
    env: dev
    dc: US
spec:
  containers:
  - name: "mycon1"
    image: "vimal13/apache-webserver-php"